version: "3.5"

services:
  server:
    container_name: kabikha_server
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: ["--command=./kabikha serve"]
    ports:
      - 8000:8000
    depends_on:
      - db
    # mounting host files to the volume is needed for CompileDaemon
    # to detect file changes so that it can hot reload
    volumes:
      - ./:/project

  db:
    container_name: kabikha_mysql
    image: mysql:8.0
    ports:
      - 3308:3306
    environment:
      - MYSQL_USER=kabikha
      - MYSQL_PASSWORD=kabikha
      - MYSQL_ROOT_PASSWORD=kabikha
      - MYSQL_DATABASE=kabikha
    volumes:
      - kabikha_data:/var/lib/mysql

volumes:
  kabikha_data:
