version: "3.5"

services:
  server:
    container_name: university_server
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: ["--command=./university serve"]
    ports:
      - 8000:8000
    depends_on:
      - db
    # mounting host files to the volume is needed for CompileDaemon
    # to detect file changes so that it can hot reload
    volumes:
      - ./:/project

  db:
    container_name: university_mysql
    image: mysql:9.2
    ports:
      - 3308:3306
    environment:
      - MYSQL_USER=university
      - MYSQL_PASSWORD=university
      - MYSQL_ROOT_PASSWORD=university
      - MYSQL_DATABASE=university
    volumes:
      - university_data:/var/lib/mysql

volumes:
  university_data:
