app:
  port: 8000
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 30

database:
  host: db
  port: 3306
  name: university
  username: university
  password: university
  ssl_mode: disable
  debug: true
