name: Docker Build

on:
  pull_request:
    branches:
      - 'main'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.6.0

      - name: Build
        uses: docker/build-push-action@v6.1.0
        with:
          push: false
          tags: aniskhan001/university:latest
